
BBBBB BBBBBBB
BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBX XX XXX
    XXXXXXX
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXX

            XX XXXXXX XXXXX XXXX XXXXXXXXXX XX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXXX XXX XXXX XXXX XX XXXXXXXXXXX XXXXXXX XXXX XXX
    XXXX  XXXXXX XXXX XXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'brandLogo') X XXXXXXXXXXXXXXX XX
                    XXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                    XXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBXX gettext(u'Services') XXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX
                    XXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXX
                    XXXXX
                    XXXX XXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Portfolio') XXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Project') XXXXXXXXX
                            XXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Project Detail') XXXX
                            XXXXX
                        XXXXX
                    XXXXX XXX
                    XXXX
                        XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
                    XXXXX
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact') XXXX
                    XXXXX
                XXXXX
    
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'facebook') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'instagram') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'linkedin') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'youtube') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXX XXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXX XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        XXXXXX
                    BBBB
                        XXXX XXXXXXX XX XXXX XXXXXXXXXXX XXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXX gettext(u'Language Selector') XXXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXX
                        XXXX
                            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of Spain') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                     gettext(u'ESP') 
                                XXXXXXXXX
                            XXXXXXX
                        XXXXX
                        XXXX
                            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of UK') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                     gettext(u'ENG') 
                                XXXXXXXXX
                            XXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'logo') X XX
                        XXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXX gettext(u'Services')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Our Services') XXXXXXXXX
                                XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                                XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                                XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                            XXXXX
                        XXXXX
                        XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About Us') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact Us') XXXXXXXXX
                        
                        XXXX XXXXX XX XXXXXXX XX XX XXXX XXXXX XXX
                        XXX XXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBB
                                XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                            BBBB
                                XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                            BBBBB
                        XXXXX
                    XXXXX
                XXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXXXXX
    XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXX
            XXXXXX
            BB BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
        
        XXXXXXX
            XXXXXXXXXXXXXXX X
                XXXXXXXXXX XXXXXX
                XXXXXXX XXXXX
                XXXXXXXX XXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXX XXX XXXXX XXXXXXXX
                XXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            X
        
            XXXXXXXXXXXX X
                XXXXXXXXXXXXXX XXXXX
                XXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXX XX X
                XXXXXXXXXX XXXXX
                XXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXX X
                XXXXXXXXXX XXXXXXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXX X
                XXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXX XXX X
                XXXXXXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX X
                XXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXX XXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XX X
                XXXXXXXXXX XXXXXXX
                XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
                XXXXXX XXXXXXXX
            X
        
            XXXXXXXXXXXXX XX X
                XXXXXXXXXX XXXXXXXX
                XXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXX XXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX X X
                XXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXX XXXXX
                XXXXXXXXXX XXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX X X
                XXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXX
            X
        
            XXXXXXXXXXXXX XXXXXXX X
                XXXXXXXXXXXXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XXXXXX X
                XXXXXXXXXXXX XXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XX X
                XXXXXXXXXXX XXXXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXX XXXX XX
                XXXXXXXX XXXX XXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXX XXX XXXXX XXXXXXXX
                XXXXXXXXXXX XXXXXXX
                XXXXXX XXXXX
            X
        
            XXXXXXXXXXXXX XXXXXXXXXX X X
                XXXXXXX XX
            X
        XXXXXXXX
        
XXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Logo') X XXXXXXXXXXXXXXXXX XX
                        XXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Company') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact us') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Services') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX                        
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Legal') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Privacy Policy') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Terms & Conditions') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXX gettext(u'© Stregasoft 2024') XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Back to Top')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX
    
    XXXX XX XXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
    XXXXXXXXX
    
    XXXX XXXXXXXX XXXXXX XXX
    XXXXXXX
    XXXXXXX
BBBBBBBB
