BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXXX XXXXXXBBBBBBBB
BBBBB BBBBBBB
  XXXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXXXXXX
  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
BBBBBBBB
