BBBBB BBBBBBB
XXXXBB BBBBBBBBBBBBBBBBXXXXBBBBXXXXXXBBBBB XXXX XXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
BBBBBBBB

XXXXXXX
  XXXX X
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXXX XXXX
  X

  XX X
      XXXXXXXXXX XXXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXX XXXXXXX
  X

  XXXX X
      XXXXXXXXXX XXXXXX
      XXXXXXX XXXXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXX
  X

  XXXXX X
      XXXXXXXXXXXX XXXXX
      XXXXXXXX XXXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXX 
  XXXXXXXXX 
  XXXXXX X
      XXXXXX XXXXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXX XXX XXXXX XXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXX
  X

  XXXXXXXX X
      XXXXXXX XXXXXX
      XXXXXXX XXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
  X

  XXXXXXXXX X
      XXXXXXXX XXXXXXXXXXXXX
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX XXXXXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXX
      XXXXXXX XXXXXXXX
      XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XX XXXXXX XXXX XXXXXXXXXX X XXXXXX XX
  XXXXXXXXXXXXXXXXXXXXX X
      XXXXXX XXXXX
      XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXX XXXXXXX
      XXXXXX XXXXXXXX
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXX XXXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXX XXXXX
      XXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XXXXXX X
      XXXXXXXXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXX XXXX XX
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXX XXX XXXXX XXXXXXXX
      XXXXXXXXXXX XXXXXXX
      XXXXXX XXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X X
      XXXXXXX XX
  X
XXXXXXXX
