BBBB BBBBBB

BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXX

            XX XXXXXX XXXXX XXXX XXXXXXXXXX XX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXXX XXX XXXX XXXX XX XXXXXXXXXXX XXXXXXX XXXX XXX
    XXXX  XXXXXX XXXX XXX
  XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'brandLogo') X XXXXXXXXXXXXXXX XX
                XXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX  XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBXX gettext(u'Services') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                    XXXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXX
                XXXXX
                XXXX XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Portfolio') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Project') XXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Project Detail') XXXX
                        XXXXX
                    XXXXX
                XXXXX XXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
                XXXXX
                XXXX
                    XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact') XXXX
                XXXXX
            XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'facebook') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'instagram') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'linkedin') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'youtube') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXX XXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBB
                    XXXX XXXXXXX XX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXX gettext(u'Language Selector') XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of Spain') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ESP') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of UK') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ENG') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'logo') X XX
                    XXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX gettext(u'Services')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Our Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX
                    XXXXX
                    XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About Us') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact Us') XXXXXXXXX
                    
                    XXXX XXXXX XX XXXXXXX XX XX XXXX XXXXX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBB
                            XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBBB
                    XXXXX
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXXXXX
XXXXXX
            XXXX  XXXXXXXXXX XXXX XXX

            XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Leave us a message!') XXXXX
            
                        XXXXX XXXXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXX XXXXXXX XXXXXXXX XX XXXXX X XXXXX XXX
                            BB BBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXX
                                    BBB BBBBBBB BB BBBBBBBB
                                        XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                            
                                        XXXXXX
                                    BBBBBB
                                XXXXXX
                            BBBBB
                        
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX gettext(u'Your Name') XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                                BB BBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBB
                                    XXXXXXX
                                    BBBBBB
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXX gettext(u'Your Last Name') XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                                BB BBBBBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                                    XXXXXXX
                                    BBBBBB
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX gettext(u'Your Email') XXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                                BB BBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBBB
                                    XXXXXXX
                                    BBBBBB
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX gettext(u'Phone (optional)') XXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                                BB BBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBBB
                                    XXXXXXX
                                    BBBBBB
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXX gettext(u'Your Message') XXXXXXXX
                                XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                                    XXXXXXX
                                    BBBBBB
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BB BBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXX
                                XXXXXX
                                BBBBB
                            XXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Send Message') XXXXXXXXX
                        XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Get in Touch') XXXXX
                            XXXX XXXXX XXX XXXXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                                    XXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
                                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX
                                            XXXXXXXX gettext(u'Chat on Whatsapp') XXXXXXXXX
                                        XXXX
                                    XXXX
                                    
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                                    XXXX
                                    XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Email:') XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                                        XXXX XXX XXX XXXXX XXXXXXXXX XXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Website:') XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Feel free to contact us for any inquiries or assistance.') XXXX
                            XXXXXX
                            
                            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Our Business Hours') XXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXX
                                XXXX
                                    XXXX gettext(u'Mon-Fri') XXXXX
                                    XXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXX XX X XXXX XXXXXXX
                                XXXXX
                                XXXX
                                    XXXX gettext(u'Sat-Sun') XXXXX
                                    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Closed') XXXXX
                                XXXXX
                            XXXXXXXX
                            
                            XXXX XXXXXXX XX XXXXX XXXX XXX
                            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            
                            XXXXXXX
                                XXXXXXXXXXXXXXX X
                                    XXXXXX XXXXX XX XXXXXXX XX XXXXX XX XX XXXXX XX
                                    XXXXXXXXXXXXXX XXXXX
                                    XXXXXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXXXXXXX XXXXX XX XXXXXXX XX XXXXXXXXXX XXXXXXXX XX
                                X
                    
                                XXXXXXXXXXXXXXX XX X
                                    XXXXXXXX XXX XXXXX XX XXXXXXX XX XXXXXXX XX
                                    XXXXXXXXXX XXXXX
                                    XXXXXX XXXXX
                                    XXXXXXXXXXX XXXXXXX XX XXXXXXX XX XXXXX XX XXX XXXXXX XX
                                X
                    
                                XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
                                    XXXXXXXXXXXX XXXXX
                                X
                    
                                XXXXXXXXXXXXXXX XXXXXXXXXXXXX X
                                    XXXXXXXXXXXX XXXXX
                                X
                            XXXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    
                    
            XXXXXXXXXX
            
            
            XXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
                    XXXXXX XXXXX
                    XXXXXXXX XXXXX
                    XXXXXXX XXX XX
                    XXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX XXX XXXXX XXXXX
                    XXXXXXXXXXXXXX XXXX
                    XXXXXXXXXX XXXXX
                    XXXXXXXXXXXX XXXX
                X
            
                XXXXXXXXXXXXXXXX X
                    XXXXXXX XXXXXXXXX
                X
            XXXXXXXX

        XXXX  XXXXXX XXXX XXX
        XXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XX XXXXXXBBB BBBBBBBXX
                                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Logo') X XXXXXXXXXXXXXXXXX XX
                                XXXX
        
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXX gettext(u'Company') XXXXX
                                XXXX
                                    XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact us') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                                XXXXX
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXX gettext(u'Services') XXXXX
                                XXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                                XXXXX                        
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXX gettext(u'Legal') XXXXX
                                XXXX
                                    XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Privacy Policy') XXXXXXXXX
                                    XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Terms & Conditions') XXXXXXXXX
                                XXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXX gettext(u'© Stregasoft 2024') XXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Back to Top')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXX
            
            XXXX XX XXXX XXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
            XXXXXXXX XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXX XXXXXXXXXX
            X
            XXXXXXXXX
            XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                    XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXX XX X
                        XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
                    X
                XXX
            XXXXXXXXX
            
            XXXX XXXXXXXX XXXXXX XXX
            XXXXXXX
            XXXXXXX
            