BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXXXX
        XX XXXXXX XXXXXXX XXX XXXXXX XX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXXXX XXXXXXX
        X

        XX XXXXXX XXX XXXXXXXXXX XXX XXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
        X

        XX XXXXXXXXX XXXXX XXXX XX XXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X

        XX XXXXXX XXX XXXXXX XXXXXXXXX XX
        XX X
            XXXXXXXXXX XXXXX
            XXXXXXX XX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X

        XX XXXXXX XXX XXXXX XXX XXXXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXX XXXX XX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
        X

        XX XXXXXX XX XXX XXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X X
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXX XXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX XXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXX
            X

            XX X
                XXXXXXXXXX XXXXXXX
            X

            XXXXXXXXXXXXXXX X
                XXXXXXXXXX XXXXX
            X

            XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXX XXXXXXX
                XXXX XXXXX
            X

            XXXXXXXXXXXXXXXX X X
                XXXXXXXX XXX XXXXX
            X
        X

        XX XXXXXX XX XXXXX X XXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXXX
            XXXXX XXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXXXX XXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBBB BBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Welcome, ') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'This is your dashboard. You can see your profile details here.') XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBXX gettext(u'Logout') XXXX
            XX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXX XXXXXXXXX XXXXX XXX XXXXXXXXX XXX
XXXXXXX
XXXXXXX
