BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Email Confirmation') XXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXX
        X
        XX X
            XXXXXX XXXXXXXX
        X
        X X
            XXXXXXX XXXX XX
        X
        XXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXX XXXXXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX XXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX gettext(u'Welcome to Stregasoft!') XXXXX
    XXX gettext(u'Hello')  XXXXXX
    XXX gettext(u'Please verify your email by clicking on the following link.') XXXX
    XXXXX XXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Confirm your Email') XXXXXXXX
XXXXXXX
XXXXXXX