BBBB BBBBBB

BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXX

            XX XXXXXX XXXXX XXXX XXXXXXXXXX XX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBB
XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
    XXXXXXXX gettext(u'Message') XXXXXXXXXX 
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
XXXXXX
BBBBBB

    XXXXXXX XXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXXX XXX XXXX XXXX XX XXXXXXXXXXX XXXXXXX XXXX XXX
    XXXX  XXXXXX XXXX XXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'brandLogo') X XXXXXXXXXXXXXXX XX
                XXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBXX gettext(u'Services') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                    XXXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXX
                XXXXX
                XXXX XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Portfolio') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Project') XXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Project Detail') XXXX
                        XXXXX
                    XXXXX
                XXXXX XXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact') XXXX
                XXXXX
            XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'facebook') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'instagram') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'linkedin') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'youtube') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXX XXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBB
                    XXXX XXXXXXX XX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXX gettext(u'Language Selector') XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of Spain') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ESP') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of UK') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ENG') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                XXXXX
            XXXXXX
            
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'logo') X XX
                    XXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX gettext(u'Services')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Our Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX
                    XXXXX
                    XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About Us') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact Us') XXXXXXXXX
                    
                    XXXX XXXXX XX XXXXXXX XX XX XXXX XXXXX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBB
                            XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBBB
                    XXXXX
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXXXXX
XXXXXX
    
       XXXX  XXXXXX XXXX XXX
       XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'mask') XX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Welcome!') XXXXX
              XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Technology at your Service') XXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Start Now!') XXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
               gettext(u'Your browser does not support the video tag.') 
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Website Logo') X XXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX
      

      
      
      
      
      
    
     XXXX  XXXXXXXXXXX XXXX XXX
XXXX  XXXXXXXXXXX XXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBXX
                    XXXXXX gettext(u'Our Services') XXXXXXX
                XXXX
            XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXX XXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Web Services logo') X XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXX
                                 gettext(u'At Stregasoft, our web development services provide tailored, innovative solutions with responsive design, ensuring a seamless user experience and robust functionality for your business growth.') 
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'CRM Services logo') X XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXX
                                 gettext(u'At Stregasoft, our CRM Services optimize customer management, enhance sales processes, and boost satisfaction with efficient, user-friendly tools customized to meet your business needs.') 
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Chatbot Services logo') X XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXX
                                 gettext(u'At Stregasoft, our chatbot services offer advanced automation for customer interactions, improving engagement and operational efficiency with intelligent, real-time support tailored to your needs.') 
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'IT Services logo') X XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXX
                                 gettext(u'At Stregasoft, our IT services deliver comprehensive support, from managing your infrastructure to implementing robust cybersecurity solutions, ensuring your technology operates securely and smoothly.') 
                            XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX



XXXX  XXXXXXXX XXXX XXX
XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Our Company') XXXXX
            XXX gettext(u'Welcome to Stregasoft, your gateway to a world of innovative tech solutions and digital excellence.') XXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Leading Technology Solutions') X XXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Leading Technology Solutions') XXXXX
                        XXX gettext(u'Our company leads the way in technology, providing a wide array of services to cater to your distinctive software and IT requirements.') XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Industry Leading Experts') X XXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Industry Leading Experts') XXXXX
                        XXX gettext(u'Our exceptional team consists of engineers, programmers, designers, and marketing experts, all dedicated to driving your ideas to the top of your industry.') XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Excellent Customer Service') X XXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Excellent Customer Service') XXXXX
                        XXX gettext(u'Our excellent customer service provides you unparalleled support and guidance. We prioritize your satisfaction and aim to build lasting relationships through our exceptional service.') XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Custom Solutions') X XXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Custom Solutions') XXXXX
                        XXX gettext(u'We are a premier provider of software services, offering personalized software solutions, expert advisory, and cutting-edge app and web design.') XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX


XXXX  XXXXX XXXX XXX

   
   

XXXX XXXXXX XXXXXX XXXXXXXXXXX XXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
         gettext(u'Your browser does not support the video tag.') 
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u"Innovation is the lifeline of entrepreneurship. It's about solving problems and creating opportunities.") XXXXXX


        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Read More') 
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Leave us a message!') XXXXX

            XXXXX XXXXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXX XXXXXXXX XX XXXXX X XXXXX XXX
                BB BBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
                                
                            XXXXXX
                        BBBBBB
                    XXXXXX
                BBBBB
            
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX gettext(u'Your Name') XXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                    BB BBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXX gettext(u'Your Last Name') XXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX gettext(u'Your Email') XXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                    BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX gettext(u'Phone (optional)') XXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXX
                    BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXX gettext(u'Your Message') XXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXX
                    BBBBB
                XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Send Message') XXXXXXXXX
            XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Get in Touch') XXXXX
                XXXX XXXXX XXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX
                                XXXXXXXX gettext(u'Chat on Whatsapp') XXXXXXXXX
                            XXXX
                        XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXX
                        XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Email:') XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXX XXX XXXXX XXXXXXXXX XXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Website:') XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Feel free to contact us for any inquiries or assistance.') XXXX
                XXXXXX
                
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Our Business Hours') XXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXX
                    XXXX
                        XXXX gettext(u'Mon-Fri') XXXXX
                        XXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXX XX X XXXX XXXXXXX
                    XXXXX
                    XXXX
                        XXXX gettext(u'Sat-Sun') XXXXX
                        XXX XXXXXXXXXXXXX XXXXXX gettext(u'Closed') XXXXX
                    XXXXX
                XXXXXXXX
                
                XXXX XXXXXXX XX XXXXX XXXX XXX
                XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXX
                    XXXXXXXXXXXXXXX X
                        XXXXXX XXXXX XX XXXXXXX XX XXXXX XX XX XXXXX XX
                        XXXXXXXXXXXXXX XXXXX
                        XXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXX XXXXX XX XXXXXXX XX XXXXXXXXXX XXXXXXXX XX
                    X
        
                    XXXXXXXXXXXXXXX XX X
                        XXXXXXXX XXX XXXXX XX XXXXXXX XX XXXXXXX XX
                        XXXXXXXXXX XXXXX
                        XXXXXX XXXXX
                        XXXXXXXXXXX XXXXXXX XX XXXXXXX XX XXXXX XX XXX XXXXXX XX
                    X
        
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
                        XXXXXXXXXXXX XXXXX
                    X
        
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXX X
                        XXXXXXXXXXXX XXXXX
                    X
                XXXXXXXX
            XXXXXX
        XXXXXX
        
XXXXXXXXXX


XXXX XXXXXX XXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Logo') X XXXXXXXXXXXXXXXXX XX
                        XXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Company') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact us') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Services') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX                        
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Legal') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Privacy Policy') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Terms & Conditions') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXX gettext(u'© Stregasoft 2024') XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Back to Top')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
   XX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XX XXXXXXXXXXXX XXXXXX XXXXXXX X XXXXXXXX XXX XXXXXXX X XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
XXXXXXX
  XXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXXXXX XX
    XXXXX XXXX
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXX XXXXXXXXX XX XX XXXXXXXX XX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXX XXXXX XX XXXXXXX XXXX XXXXXX XXX XXXXXXXXX XX
    XXXXXXXXXXX XXX XXXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
  X

  XXXXXXXXXXXXXX X X
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXX X X XXXX XX
  X

  XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXX
  X

  XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXXX XX XXXXXX XX XXXXXXXX XX
    XXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXX XXXXXXXX
  X
XXXXXXXX




XXXX XX XXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XX XXXXXX XXXXXX XX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXX
        XXX
    XXX

    XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XX
        XXXXXXXXXXXXX XXX
        XXXXXXXXXXX X
            XXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXX
        XX
        XXXXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXX X
            XXXX X
                XXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXX XXX
            XX
        XX
    XXX
XXXXXXXXX
XXXXXXXX
    XXX XXXXXXX
    XXX XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
    XX X XXXXXXXX XXXXX XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXX

        XX XXXXXXX X XXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXXX
        X
    XX X XXXXXXXX XXXXX XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBXX
    XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
                X
            XXX
        XXX
    XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXX XX X
            XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
        X
    XXX
XXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
            XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXX XXX X
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        XXX
    XXX
XXXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXXX XX XX XXXXXXX XX XX XXXXXXXX X XXXXXXXXX XXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X

    XX XXXXXXX XX XXXX XX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XX XXXX XXXXXX XXXXXXX XXXXXX XXXXXX XX XXXXXXX XXX XXXXXXXX XXX XXXXXXXX XXXXXXXXX XXXXXXXX
    XXX

    XX XXXXXXX XX XXXX XX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XX XXXX XXXXXX XXXXXXX XXXXXX XXXX XX XXX XXXX XX XX XXXXXXX XXXXXXX XXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX
    XXX
  XXX
XXXXXXXXX


XXXX XXXXXXXX XXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX    XXXXXXXXX
XXXX        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXX            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXX                XXXXX XXXXXX XXX XXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX X X XXX X X X X XXXXXXXXX XXX X X XXXX X X X X XXX XXX XXXXX
XXXX        XXXXXXXXX
XXXX    XXXXXXXXXX
XXXXXXXXXXXXX
XXXXXXX
XXXXXXX
