BBBB BBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Sign In') XXXXXXXX
    XXXX XXXXXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXX XXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXX X X XXX XXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXX X X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X

        XXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXXX
            XXXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX X XXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXXXXXX XX
            XXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X

        XXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXXXXXXXX XXXXX X
            XXXXX XX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXX XXXXX XXXXXXXX XXX
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
            XXXXXXXX gettext(u'Message') XXXXXXXXXX 
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u' Close') XX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
        BBBBBB

        XXXX XXXX XXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u' Logo') X XXXXXXXXXXXXX

        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Log In to Your Account!') XXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX gettext(u'Username') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter Your Username') X XXXXXXXXX

            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'Password') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter Your Password') X XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Log In') XXXXXXXXX
        XXXXXXX



       XXXX XXXXX XX XXXXXXXX XXX
XXXX XXXXX XX XXXXXXXX XXX
XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Continue with Facebook') 
XXXX

XXXX XXXXX XX XXXXXXXXX XXX
XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Continue with Microsoft') 
XXXX


XXXX XXXXXXX XXXXXXXXXXXXXX XXX
XXXXXXX
    XXXX X
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXX
        XXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
    X

    XXXX X X
        XXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X

    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXX X X XXX XXXXXXXX XXX XXXX XXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
    X

    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXX X X XXX XXXXXXX XX XX XXXXX
    X
XXXXXXXX

XXXX XXXXXX XXX XXXXXXXX XXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXX
     gettext(u"Don't have an account?") XX XXXXXXBBB BBBBBBBBBBXX gettext(u'Register Here!') XXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Forgot your password?') XXXX
XXXXXX



    XXXX XXXXXXX XXXXXXXXX XX XXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXXXXX