BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
            XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XX
        X

        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXXXXXX XX
            XXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X

        XXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Password Reset Sent') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXX gettext(u"We've emailed you instructions for resetting your password. You should receive them shortly.") XXXX
    XXXXXX
    
XXXXXXX
XXXXXXX
