BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
            XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXX XX
        X

        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXXXXXX XX
            XXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX XXXXXXXX
        X

        XXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXX XXXXX X XXX XXX XXXXXXX XX XX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBB
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Reset Password') XXXXX
            BB BBBBBBBB
                XXXX
                    BBB BBBBBBB BB BBBBBBBB
                        XXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    BBBBBB
                XXXXX
            BBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXXXX gettext(u'Email Address:') XXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Send Reset Link') XXXXXXXXX
            XXXXXXX
        BBBBBBBB
    XXXXXX
    
XXXXXXX
XXXXXXX
