BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Enter New Password') XXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
            XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXX
            XXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
        X

        XXXXXX XXXXXX X
            XXXXXXXXXXXX XX
            XXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XX
            XXXXXXX XXXXXXXX
        X

        XXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X

        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
        X

        XXXX XXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXXXXX XXXXX X XXX XXX XXXXXXX XX XX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX
        X

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXX XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
            XXXXXX XXXXX
        X

        XXXX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Enter New Password') XXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'New Password') XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Confirm New Password') XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Set New Password') XXXXXXXXX
        XXXXXXX
        XXXX XXXXXXX XXXX XXXXXX XXX
        BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
                XXXX XXXXXXXXXXXX  XXXXXX
                    
                XXXXXX
            BBBBBB
        BBBBB
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX
