BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
            XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX gettext(u'Password Reset Complete') XXXXX
        XX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Your password has been successfully reset. Please')  XX XXXXXXBBB BBBBBBBXX gettext(u'log in') XXXX  gettext(u'with your new password using your username. If you have forgotten your username, please check the email sent to you earlier as it contains your username. If you have any issues, please contact support.') 
        XXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Go to Login') XXXX
    XXXXXX
XXXXXXX
XXXXXXX
