BBBB BBBBBB

BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXXX XX XXX XXXX XXXXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXX

            XX XXXXXX XXXXX XXXX XXXXXXXXXX XX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX XXX XXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXXX XXX XXXX XXXX XX XXXXXXXXXXX XXXXXXX XXXX XXX
    XXXX  XXXXXX XXXX XXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'brandLogo') X XXXXXXXXXXXXXXX XX
                XXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
                    XX  XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                XXXXX
                XXXX
                    XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Services') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                        XXXXXX  XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                        XXXXXX  XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                        XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                    XXXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXX
                XXXXX
                XXXX XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Portfolio') XXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Project') XXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Project Detail') XXXX
                        XXXXX
                    XXXXX
                XXXXX XXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXX
                XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact') XXXX
                XXXXX
            XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'facebook') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'instagram') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'linkedin') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'youtube') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXX XX XX XXXXXXX XXXX XXXXXXXXXXX XXX
                BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBB
                    XXXX XXXXXXX XX XXXX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXX gettext(u'Language Selector') XXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of Spain') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ESP') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                    XXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Flag of UK') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXX
                                 gettext(u'ENG') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXX
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBXX
                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'logo') X XX
                    XXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                    XXXX
                        XX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Home') XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX gettext(u'Services')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Our Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX
                    XXXXX
                    XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About Us') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact Us') XXXXXXXXX
                    
                    XXXX XXXXX XX XXXXXXX XX XX XXXX XXXXX XXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBB
                            XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBB
                            XX XXXXXXBBB BBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'account') X XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX
                        BBBBB
                    XXXXX
                XXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXXXXX
XXXXXX
        XXXX  XXXXXXXXXX XXXX XXX
        XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX X
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXX gettext(u'Web Portfolio')  XXXXX
                              XXXXXX
                              XXX
                                 gettext(u'Explore our diverse portfolio showcasing the range of web solutions we offer. From dynamic websites to innovative digital platforms, each project reflects our commitment to excellence and our ability to tailor solutions to meet specific client needs.') 
                              XXXX
                          XXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                          XXXXXX
                      XXXXXX
                  XXXXXX
                  
                      XXXXXX
                  XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
        

XXXX XXXX XXXXX XX XXXXXXXXXXXXXX XXX XXXXXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
  
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXX XXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
          
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
          
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXX
        XXXXXX


        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
          
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
           
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXX XX
                XXXX
            XXXXXX
            
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXX XXXX XX
                XXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXX
        XXXXXX

    XXXXXX
XXXXXXXXXX


 
        XXXX  XXXX XX XXXXXX XXXX XXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXX gettext(u'Have Any Project On Mind? Contact Us!') XXXXX
                            XXX
                                 gettext(u"Let's connect! Contact us today for expert assistance and turn your ideas into reality.") 
                            XXXX
                            XX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Send Message') XXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Call To Action') X XX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'mask') X XX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
   XXXX  XXXXXX XXXX XXX
   XXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBXX
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Logo') X XXXXXXXXXXXXXXXXX XX
                        XXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Company') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'About') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact us') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBXX gettext(u'Blog') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Services') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Web Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'CRM Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXX gettext(u'Chatbot Services') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'IT Services') XXXXXXXXX
                        XXXXX                        
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'Legal') XXXXX
                        XXXX
                            XXXXXX XXXXXXBBB BBBBBBBBBXX gettext(u'Privacy Policy') XXXXXXXXX
                            XXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Terms & Conditions') XXXXXXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXX gettext(u'© Stregasoft 2024') XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Back to Top')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXXX
    
    XXXX XX XXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX XXXXXXXXXX
    X
    XXXXXXXXX
    
    XXXX XXXXXXXX XXXXXX XXX
    XXXXXXX
    XXXXXXX
    