BBBB BBBBBB
BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Sign Up') XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX XX XXXX XXXXX XXX XXXX XXXXXXXX XX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXX
            XXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
        X

        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXX X X XXX XXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXX X X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X

        XX XXXX XXXXXX XX
        XXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XX XXXXX XXXXXX XX
        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXX XXXXX XX
            XXXXXX XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXXX
            XXXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX X XXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
        X
        
        XXXXXX XXXXXX X
            XXXXXXXXXXXX XX
            XXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXX XX
        X
        
        XXXXXX XXXXXXXXXXXX X
            XXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXXX XXXXXXXXXXXX XX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXXX XXXXXXXXXXXX XX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXX XXXXXXXXXXXX XX
            XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XX XXXX XXXXXXXXXXXX XX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXX XXXXX
            XXXXXX XXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXX
          X
          XXXXXXXXXXXXXXXX X
              XXXXXX XXXXXXXX
            X
            XXXXXXXXXXXXXXX X
                XXXXXXXXX XXXXXXXXX
            X
            
            XXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXX
                XXXXXXXXXXXX XXXXXXX
            X
            
            XXXXXXXXXXXXXXXX X
                XXXXXXXXX XXXXXXXXX
                XXXXXX XXXXX
                XXXXXXX XXXXXXXX
                XXXXXXXXXX XXXXX XX XXXXXX XX XXXXXX XXXXX XXX XXXXXXXXX XX
                XXXXXX XXXXXXXX  XX XXXXXX XX XXXXX XXXXX XX XXXXXX XX
            X
    XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Sign Up') XXXXXX
        BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Close') XX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBB
        
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX gettext(u'Username') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'First Name') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'Last Name') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'Email address') XXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'Password') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX gettext(u'Confirm Password') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Register') XXXXXXXXX
        XXXXXXX
        XXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X XXXXXX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXX
            X
            
        XXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Already have an account?')  XX XXXXXXBBB BBBBBBBXX gettext(u'Log In') XXXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXXXXX
